/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Sample1_delayedInit__body */

#ifndef _Included_example_Sample1_delayedInit__body
#define _Included_example_Sample1_delayedInit__body
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
