/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Sample1 */

#ifndef _Included_example_Sample1
#define _Included_example_Sample1
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     example_Sample1
	* Method:    intMethod
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_example_Sample1_intMethod
		(JNIEnv *, jobject, jint);

	/*
	* Class:     example_Sample1
	* Method:    booleanMethod
	* Signature: (Z)Z
	*/
	JNIEXPORT jboolean JNICALL Java_example_Sample1_booleanMethod
		(JNIEnv *, jobject, jboolean);

	/*
	* Class:     example_Sample1
	* Method:    stringMethod
	* Signature: (Ljava/lang/String;)Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_example_Sample1_stringMethod
		(JNIEnv *, jobject, jstring);

	/*
	* Class:     example_Sample1
	* Method:    intArrayMethod
	* Signature: ([I)I
	*/
	JNIEXPORT jint JNICALL Java_example_Sample1_intArrayMethod
		(JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
